/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:82079d1b-95ec-45ff-9729-8eca5188b11d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZO9RVZu8m",
    "aws_user_pools_web_client_id": "6pukd0i3d0g1qj20bvnv5059sa",
    "oauth": {
        "domain": "projecttracker46100bbc-46100bbc-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://szpt.netlify.app/googleredirect",
        "redirectSignOut": "https://szpt.netlify.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ipftclnq4basxhwmuxm3g7fv2u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-at5vhidwjresrpskyr6ebh4db4",
    "aws_user_files_s3_bucket": "projecttracker096cf5e8bd4c4c5d84aa24fa3ee80bb2231317-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
